
PS C:\WINDOWS\system32> docker run --name h2-vetlink -d --network vetlink-network -p 8082:8082 -p 9092:9092 -v h2-vetlink-data:/opt/h2-data oscarfonts/h2
Unable to find image 'oscarfonts/h2:latest' locally
latest: Pulling from oscarfonts/h2
66223a710990: Pull complete
d9d4b9b6e964: Pull complete
9daef329d350: Pull complete
d85151f15b66: Pull complete
4f4fb700ef54: Pull complete
2068746827ec: Pull complete
db38d58ec8ab: Pull complete
90a597539f75: Pull complete
001c52e26ad5: Pull complete
26688a57eb43: Pull complete
90e04ad67386: Pull complete
1074a07aca9a: Pull complete
Digest: sha256:923ff3cb753c455ced9e99bcfa9feb567740f3dfb842ab68ce10f9edf40928cf
Status: Downloaded newer image for oscarfonts/h2:latest
531c254d29a893b8f36ab6755b292403a7c389bc119063ed7b8dfe6176def385
PS C:\WINDOWS\system32> docker ps
CONTAINER ID   IMAGE           COMMAND                  CREATED         STATUS         PORTS                                                              NAMES
531c254d29a8   oscarfonts/h2   "/bin/sh -c 'java -c?"   7 seconds ago   Up 7 seconds   81/tcp, 0.0.0.0:8082->8082/tcp, 1521/tcp, 0.0.0.0:9092->9092/tcp   h2-vetlink
PS C:\WINDOWS\system32>